version: '3.9'

volumes:
  mysql_data: {}
  apache_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/projeto  # Altere para o diretório desejado

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./path/to/your/laravel/code:/var/www/html
      - apache_logs:/root/projeto  # Mapeando o volume para /root/projeto
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=projeto
      - DB_USERNAME=projeto
      - DB_PASSWORD=projeto
    command: >
      bash -c "git clone https://github.com/Gabrielkoeric/gerenciador_de_maquinas.git /var/www/html &&
               cp /var/www/html/gerenciador_de_maquinas/.env.example /var/www/html/gerenciador_de_maquinas/.env &&
               sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/gerenciador_de_maquinas/public|' /etc/apache2/sites-available/000-default.conf &&
               sed -i 's|<Directory /var/www/html>|<Directory /var/www/html/gerenciador_de_maquinas/public>|' /etc/apache2/apache2.conf &&
               cd /var/www/html/gerenciador_de_maquinas &&
               composer install --no-dev --optimize-autoloader &&
               php artisan key:generate --force &&
               chown -R www-data:www-data /var/www/html/gerenciador_de_maquinas/storage /var/www/html/gerenciador_de_maquinas/bootstrap/cache &&
               a2enmod rewrite &&
               apache2-foreground"